In [1]:
import sympy as sp
import numpy as np
import math

In [2]:
C = np.array([
        [0.2, 0.0, 0.2, 0.0, 0.0], 
        [0.0, 0.2, 0.0, 0.2, 0.0], 
        [0.2, 0.0, 0.2, 0.0, 0.2], 
        [0.0, 0.2, 0.0, 0.2, 0.0], 
        [0.0, 0.0, 0.2, 0.0, 0.2]
        ])
D = np.array([
        [ 2.33,  0.81,  0.67,  0.92, -0.53], 
        [ 0.81,  2.33,  0.81,  0.67,  0.92], 
        [ 0.67,  0.81,  2.33,  0.81,  0.92], 
        [ 0.92,  0.67,  0.81,  2.33, -0.53], 
        [-0.53,  0.92,  0.92, -0.53,  2.33]
        ])
A = 8 * C + D

In [ ]:
A[0,1]+=0.001
A[2,3]+=0.001
A[4,1]-=0.001
A[3,3]+=0.001
A[1,4]-=0.001

In [ ]:
def find_max_not_diag_elem(A):
  max_elem=abs(A[0,1])
  max_elem_index=[0,1]
  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
      if i!=j and j>i:
        if abs(A[i,j])>abs(max_elem):
          max_elem=A[i,j]
          max_elem_index[0]=i
          max_elem_index[1]=j
  i_max,j_max=max_elem_index
  return i_max,j_max

In [ ]:
def calc_p(A,i_max,j_max):
  if A[i_max,i_max]!=A[j_max,j_max]:
    Pij=2*A[i_max,j_max]/(A[i_max,i_max]-A[j_max,j_max])
  else:
    Pij=math.pi/4
  return Pij

In [ ]:
def cos_sin(Pij):
  c=cos_Fi = np.sqrt(0.5*(1+(1+Pij**2)**-1))
  s=sin_Fi = np.sqrt(0.5*(1-(1+Pij**2)**-1))
  return c,s

In [ ]:
def Jcobi_method(A,key=2):
  Matrix_array=[]
  ansV=np.eye(A.shape[0])
  k=0
  delta=1
  while delta>0.0001:
    i_max,j_max=find_max_not_diag_elem(A)
    V=np.zeros(A.shape)
    Pij = calc_p(A,i_max,j_max)
    if key==1:
      c,s = cos_sin(Pij)
    elif key==2:
      c = np.cos(1/2 * np.arctan(Pij))
      s = np.sin(1/2 * np.arctan(Pij))
    else:
      return 0
    cos_Fi=c
    sin_Fi=s

    V = np.eye(A.shape[0])
    V[i_max,i_max]=cos_Fi
    V[j_max,j_max]=cos_Fi
    V[i_max,j_max]=-sin_Fi
    V[j_max,i_max]=sin_Fi

    A=np.dot(np.dot(V.transpose(),A),V)

    ansV=np.dot(ansV,V)
    delta=(A**2).sum()-((A**2).diagonal()).sum()
    k+=1
  return A.diagonal(),ansV,k

In [ ]:
def QR_method(A):
  delta=1
  k=0
  ansQ=np.eye(A.shape[0])
  while delta>0.0001:
    Q,R=np.linalg.qr(A)
    #A=np.dot(np.dot(Q,R),Q.transpose())
    A=np.dot(np.dot(Q.transpose(),A),Q)
    delta=(A**2).sum()-((A**2).diagonal()).sum()
    k+=1
    ansQ=np.dot(ansQ,Q)
  return A.diagonal(),ansQ,k

In [ ]:
QR_method(A)

In [ ]:
def main(A):
  eigenvalues,eigenvectors,k=Jcobi_method(A,key=2)
  eigenvectors1=eigenvectors
  eigenvalues1=eigenvalues
  print(f"Метод Якоби\n")
  print(f"Собственные значения = \n{eigenvalues}\n")
  print(f"Собственные вектора = \n{eigenvectors}\n")
  print(f"Количество опреаций = {k}\n-------------")

  eigenvalues,eigenvectors,k=QR_method(A)
  eigenvectors2=eigenvectors
  eigenvalues2=eigenvalues
  print(f"\nQR метод\n")
  print(f"Собственные значения = \n{eigenvalues}\n")
  print(f"Собственные вектора = \n{eigenvectors}\n")
  print(f"Количество опреаций = {k}\n-------------")

  print(f"\nПравильный ответ \n{np.linalg.eigh(A)[0]}\n\n{np.linalg.eigh(A)[1]}")
  return eigenvectors1,eigenvalues1,eigenvectors2,eigenvalues2

In [ ]:
eigenvectors1_change,eigenvalues1_change,eigenvectors2_change,eigenvalues2_change=main(A)

In [ ]:
eigenvectors1_origin,eigenvalues1_origin,eigenvectors2_origin,eigenvalues2_origin=main(A)

In [ ]:
eigenvalues2_change

array([8.28890765, 5.51930842, 4.147317  , 1.61707119, 0.07839574])

In [ ]:
eigenvalues2_origin

array([8.28862463, 5.51875722, 4.14804248, 1.61624866, 0.07832702])

In [ ]:
round(np.linalg.norm(eigenvalues2_change-eigenvalues2_origin),7)

0.0012616

In [ ]:
eigenvalues1_change=np.array([4.14730814,8.28890627,5.5193173,1.61706313,0.07840515])

In [ ]:
#eigenvalues1_change

In [ ]:
eigenvalues1_origin

array([4.14803285, 8.28862321, 5.51876685, 1.61623894, 0.07833815])

In [ ]:
round(np.linalg.norm(eigenvalues1_change-eigenvalues1_origin),7)

0.0012618